### PR TITLE
Add  support to read and match pattern against whole log entry instead of a single line

### PR DESCRIPTION
**Pull request by jhshadi**
## Pull Request Checklist

**Is this in reference to an existing issue?**
[#18](https://github.com/sensu-plugins/sensu-plugins-logs/issues/18)

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
Add the ability to read and match whole log entry in the log file instead of single line.

### CODE REVIEW

**Comment by majormoses** [comment]
@jhshadi can you rebase to fix conflicts?

**Comment by majormoses** [comment]
Also what are the resource (memory) implications here? This feels unbounded and we may want to at least warn the user if their pattern is a certain length or complexity?

**Comment by majormoses** [comment]
looks like there are still conflicts, you can fix this by setting this repo as the upstream and rebasing against it:
1. setup upstream
1. `git fetch upstream`
1. `git checkout master`
1. `git rebase upstream/master`
1. fix any conflicts
1. `git add $CONFLICTING_FILES`
1. `git rebase --continue`
1. once you are done you need to force push with `git push -f`

**Comment by majormoses** [comment]
@eheydrick do you have any thoughts on appropriate safeguards, warnings, etc on this? With a poor regex this could consume a lot of memory.

**Comment by jhshadi** [comment]
@majormoses what kind of solution do you have in mind?
since there's no limit or boundary on a single line your concern is applied to the current implementation as well if i understand you right.

I have consider adding a boundary to the log entry lines (let's say 500 lines max per log entry or even expose the number of log line as an option).

**Comment by majormoses** [comment]
@jhshadi yes there probably is risk even with it being single line being massive though the risk of that is arguably smaller since it's scope is inherently limited (hopefully you don't have say 20GB of text on a single line but I suppose its possible say logging out the data returned from say a database query), my concern is that someone tries say a pattern that accidentally includes say the whole log file as a single search loading the entire file into memory (as opposed to loading it line by line and checking that) which I have seen places that do not have proper log rotation and very massive log files. I would probably start with forbidding regex ending with a wildcard to prevent this. Beyond that I honestly need to think about this more.

**Comment by majormoses** [comment]
I have thought of this and we could try to at least catch a few unbound regexes with little ease:

- `regex.end_with?('*')`
- `regex.end_with('[a-z-A-Z]+')`
- `regex.end_with('.+')`

**Comment by eheydrick** [comment]
At a minimum we should document the potential performance implications. IMO log analysis tools like Logstash or Graylog are better suited for this kind of log checking.

**Comment by majormoses** [comment]
@jhshadi can you put together something in readme about this?

**Comment by jhshadi** [comment]
@majormoses sure, but i'm not exactly sure what to add and where.

**Comment by majormoses** [comment]
@jhshadi I was looking for something along these lines: https://github.com/sensu-plugins/sensu-plugins-logs/pull/19/commits/07b24269067d7cca43e8c1c965f88c6e1e02dc1b

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-logs/versions/1.1.0

**Pull request merged**
