### PR TITLE
Fix 'crit' and 'warn' flags being ignored in search_log

### PR DESCRIPTION
**Pull request by avifried1**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by majormoses** [comment]
@avifried1 I need to review the code more and try testing this as the changes make sense when I look at it but maybe that `m[1]` had a purpose that is eluding me that will be apparent when I set this up and look at the actual data returned. I'd like to merge this but want to vett that it won't break other users.

**Comment by avifried1** [comment]
@majormoses  fair enough. I ran some tests locally on this code, and I'm not sure what was the original purpose of the m[1] (only thing I can think of is perhaps an older Ruby implementation...)
the code never enters this block, since m[1] is always empty.

**Comment by majormoses** [comment]
Ya I did some testing (against master) and do not understand this logic when I look at some really simple example data there is no clarity and I can only assume this code might have had some purpose at some point but from what I can tell `m.to_a` will always have a length of `0` or `nil` when not matched.  I am good with merging this and dealing with any weird bug reports later if there is something crazy that I don't see.

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-logs/versions/1.1.1

**Pull request merged**
