### PR TITLE
Added truncate to offset file.

### PR DESCRIPTION
**Pull request by georgespatton**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [ ] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by georgespatton** [comment]
Added a truncate to the offset file to handle large files that are not truncated often.

**Comment by majormoses** [comment]
Thanks for the contribution!

Can you expand on this a little? This feels like it is a breaking change and not something that should be default. Can you please also include a CHANGELOG entry and a testing artifact? Our PR guidelines are located here: https://github.com/sensu-plugins/community/blob/master/PULL_REQUEST_PROCESS.md

**Comment by georgespatton** [comment]
We saw that with logs that are written too often but rotated, it was changing the line number of the offset, but not correctly when the logs were rotated.  Thus, we saw high utilization of the plugin trying to seek to a part of the file that either was non-existent or past the current place in the file in which it needed to be.  The test for the commit would be to write a heavy stream of log lines to a file, watch the offset file, then logrotate at a large filesize (in our case it was around 2GB).  Once rotated, see that the offset does change correctly.  In our case, we have successfully tested this change in production and it does not cause issues.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-logs/versions/1.3.1

**Pull request merged**
