### PR TITLE
Fixed unhandled encoding exception when using the 'log-pattern' option

### PR DESCRIPTION
**Pull request by jhshadi**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by majormoses** [comment]
looks ok at a glance I need a testing artifact. @avoosh since I know you initially added this feature does this potentially break your use case?

**Comment by avihay-av** [comment]
@majormoses Nope. We're good. 👍 
Thanks.

**Comment by majormoses** [comment]
@jhshadi still need a testing artifact (something I have started taking a line in the sand on to reduce the number of times people break stuff). Overall the code looks good.

**Comment by majormoses** [comment]
closing due to inactivity, if you wish to see this through I can re-open.

**Comment by jhshadi** [comment]
@majormoses can you reopen this pr?

**Comment by jhshadi** [comment]
@majormoses 
>@jhshadi still need a testing artifact (something I have started taking a line in the sand on to reduce the number of times people break stuff). Overall the code looks good.

`example_01.log` content:
```bash
[entry] This is line 1
[entry] this is line 2
[entry] error line
[entry] this is line 3
[entry] this is another error line
[entry] this is line 4����
```
before the fix:
```bash
$ ./bin/check-log.rb --log-file test/logs/example_01.log --state-dir ./test/logs/state --pattern error --log-pattern \[entry\] --crit 1 --return
Check failed to run: invalid byte sequence in US-ASCII, ["./bin/check-log.rb:253:in `match'", "./bin/check-log.rb:253:in `match'", "./bin/check-log.rb:253:in `block in get_log_entry'", "./bin/check-log.rb:252:in `each_line'", "./bin/check-log.rb:252:in `get_log_entry'", "./bin/check-log.rb:217:in `block in search_log'", "./bin/check-log.rb:215:in `each_line'", "./bin/check-log.rb:215:in `search_log'", "./bin/check-log.rb:165:in `block in run'", "./bin/check-log.rb:159:in `each'", "./bin/check-log.rb:159:in `run'", "/Users/shlomi/.rvm/gems/ruby-2.3.3/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```

after:
```bash
$ ./bin/check-log.rb --log-file test/logs/example_01.log --state-dir ./test/logs/state --pattern error --log-pattern \[entry\] --crit 1 --return
CheckLog CRITICAL: 0 warnings, 2 criticals for pattern error. 
[entry] error line

[entry] this is another error line
```

LMK if anything else is needed to push it forward.

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-logs/versions/1.2.1

**Pull request merged**
